import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Poppins} from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const poppins = Poppins({
  subsets : ["latin"],
  variable: "--font-poppins",
  weight: ["100","200","300","400","500" ,"600" ,"700" ,"800","900"],
});

export const metadata: Metadata = {
  title: "UI Component Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
     
      <body
        className={` ${poppins.variable} `}
      >
        {children}
      </body>
      
    </html>
    </ClerkProvider>
  );
}
